<?php

/**
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * StoreApiInterfaceTest Class Doc Comment
 *
 * @link https://github.com/openapitools/openapi-generator
 */
class StoreApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteOrder
     *
     * Delete purchase order by ID.
     */
    public function testDeleteOrder(): void
    {
        $client = static::createClient();

        $path    = '/store/order/{orderId}';
        $pattern = '{orderId}';
        $data =    $this->genTestData('[a-z0-9]+');
        $path =    str_replace($pattern, $data, $path);

        $client->request('DELETE', $path);
    }

    /**
     * Test case for getInventory
     *
     * Returns pet inventories by status.
     */
    public function testGetInventory(): void
    {
        $client = static::createClient();

        $path    = '/store/inventory';

        $client->request('GET', $path);
    }

    /**
     * Test case for getOrderById
     *
     * Find purchase order by ID.
     */
    public function testGetOrderById(): void
    {
        $client = static::createClient();

        $path    = '/store/order/{orderId}';
        $pattern = '{orderId}';
        $data =    $this->genTestData('\d+');
        $path =    str_replace($pattern, $data, $path);

        $client->request('GET', $path);
    }

    /**
     * Test case for placeOrder
     *
     * Place an order for a pet.
     */
    public function testPlaceOrder(): void
    {
        $client = static::createClient();

        $path    = '/store/order';

        $client->request('POST', $path);
    }

    /**
    * @param string $regexp
    *
    * @return mixed
    *
    * @throws \Hoa\Regex\Exception
    */
    protected function genTestData(string $regexp)
    {
        $grammar   = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler  = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast       = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast);
    }
}
